class AppConstants {
  static const String fontCairo = "Cairo";
  static const String token =
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vZGV2dGVhbS53ZWJzaXRlL2JhYi1jYXIvcHVibGljL2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNzU5Mzg4NDA5LCJleHAiOjE3NTk5OTMyMDksIm5iZiI6MTc1OTM4ODQwOSwianRpIjoiNnJ4NDlWRVY2dDJDQThIUiIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.XvP-ZGAYl85mrz_ZFHly8wUqGKN9tnuBejyfZWhDj5Q";
}
